declare var MADOOP_MODE_DEBUG: any;
declare var MADOOP_SERVER_URL: any;

// `Module` declared in js generated by Emscripten
declare var Module: any;

// Called by map/reduce in C++
let execEmit: Function = null;

((): void => {

  const ROOT =
    typeof MADOOP_SERVER_URL === 'undefined' ?
    'http://localhost:3000/madoop' :
    `${MADOOP_SERVER_URL}`;

  const printLog = (msg: string): void => {
    if (typeof MADOOP_MODE_DEBUG !== 'undefined') {
      console.log(`[${new Date().toISOString()}] [INFO] - ${msg}`);
    }
  };

  const ajaxGet = async (url: string): Promise<string> => {
    return new Promise<string>((resolve, reject) => {
      const req = new XMLHttpRequest();
      req.onreadystatechange = (): void => {
        if (req.readyState !== 4) { return; }
        if (req.status.toString().charAt(0) !== '2') {
          throw new Error('[Madoop] cannot communicate with server.');
        }
        printLog(`[GET] ${url}`);
        resolve(req.responseText);
      };
      req.open('GET', url, true); // true: ensure async request
      req.setRequestHeader('Pragma', 'no-cache'); // do not use cache
      req.setRequestHeader('Cache-Control', 'no-cache'); // do not use cache
      req.send();
    });
  };

  const ajaxPost = async (url: string, data: any): Promise<string> => {
    return new Promise<string>((resolve, reject) => {
      const req = new XMLHttpRequest();
      req.onreadystatechange = (): void => {
        if (req.readyState !== 4) { return; }
        if (req.status.toString().charAt(0) !== '2') {
          throw new Error('[Madoop] cannot communicate with server.');
        }
        printLog(`[POST] ${url}`);
        resolve(req.responseText);
      };
      req.open('POST', url, true);
      req.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded;charset=UTF-8');
      req.send(data);
    });
  };

  const ajaxPostJson = async (url: string, jsonData: Object): Promise<string> => {
    let data = '';
    Object.keys(jsonData).forEach(function (key) {
      const val = this[key]; // `this` === `jsonData`
      data += `${key}=${val}&`;
    }, jsonData);
    const response = await ajaxPost(url, data);
    return response;
  };

  const sleep = async (msec: number = 1000) => {
    return new Promise<void>((resolve, reject) => {
      setTimeout(() => {
        resolve();
      }, msec);
    });
  };

  const applyScript = (script: string): void => {
    const element = document.createElement('script');
    element.text = script;
    document.head.appendChild(element).parentNode.removeChild(element);
  };

  const execFuncs = new Map<string, Function>();
  const getExecFunc = async (metaInfo: { jobId: string, phase: string }): Promise<Function> => {
    const metaInfoString = JSON.stringify(metaInfo);
    if (execFuncs.has(metaInfoString)) {
      return execFuncs.get(metaInfoString);
    }
    const gotData = await ajaxGet(`${ROOT}/wasmData/${metaInfo.phase}`);
    const wasmData: {
      wasmJs: string,
      wasmBinary: {type: string, data: Array<number>}
    } = JSON.parse(gotData);
    applyScript(wasmData.wasmJs);
    let func;
    if (metaInfo.phase === 'map') {
      await new Promise<void>((resolve, reject) => {
        let module;
        const moduleArgs = {
          'wasmBinary': new Uint8Array(wasmData.wasmBinary.data),
          'onRuntimeInitialized': () => {
            func = module.cwrap('map', null, ['string']);
            resolve();
          }
        };
        module = Module(moduleArgs);
      });
    } else if (metaInfo.phase === 'reduce') {
      await new Promise<void>((resolve, reject) => {
        let module;
        const moduleArgs = {
          'wasmBinary': new Uint8Array(wasmData.wasmBinary.data),
          'onRuntimeInitialized': () => {
            func = module.cwrap('reduce', null, ['string', 'string']);
            resolve();
          }
        };
        module = Module(moduleArgs);
      });
    } else {
      throw new Error(`[Madoop] invalid task phase provided: ${metaInfo.phase}`);
    }
    execFuncs.set(metaInfoString, func);
    return func;
  };


  const main = async (): Promise<void> => {
    while (true) {
      const next = await ajaxGet(`${ROOT}/tasks/next`);
      const task: {
        metaInfo: { jobId: string, phase: string },
        inputData: any
      } = JSON.parse(next);
      if (task.metaInfo === null) {
        await sleep(1000);
        continue;
      }
      const func = await getExecFunc(task.metaInfo);
      const result = [];
      if (task.metaInfo.phase === 'map') {
        execEmit = (key, value) => { // called by map in C++
          const element = {
            'key': key,
            'value': value
          };
          result.push(element);
        };
        func(task.inputData); // call above `execEmit` inside
      } else if (task.metaInfo.phase === 'reduce') {
        const inputDataObject: { key: any, values: any[] }[] = JSON.parse(task.inputData);
        execEmit = (key, value) => { // called by reduce in C++
          const element = {
            'key': key,
            'value': value
          };
          result.push(element);
        };
        inputDataObject.forEach(element => {
          func(element.key, element.values.toString()); // call above `execEmit` inside
        });
      } else {
        throw new Error(`[Madoop] invalid task id provided: ${task.metaInfo.phase}`);
      }
      const jsonData = {
        metaInfo: JSON.stringify(task.metaInfo),
        result: JSON.stringify(result)
      };
      await ajaxPostJson(`${ROOT}/tasks/result`, jsonData);
    }
  };
  main();

})();
